name: Build and push Image to AWS ECR
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Install Docker
      run: | 
        sudo yum install docker -y
        sudo systemctl start docker
        sudo systemctl status docker  
    - name: Build Image 
      run : |
        cd /home/ec2-user/actions-runner/_Docker/Docker/Docker
        sudo docker build -t helloworld .
    - name: Build and push ECR
      run : |
        sudo su -
        aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 443986840361.dkr.ecr.ap-southeast-2.amazonaws.com
        docker tag helloworld:latest 443986840361.dkr.ecr.ap-southeast-2.amazonaws.com/docker-repository:latest
        docker push 443986840361.dkr.ecr.ap-southeast-2.amazonaws.com/docker-repository:latest
    - name: Clean Up all
      run: |
        sudo docker rmi -f $(sudo docker images -a -q)
        sudo yum remove docker 
      
    # - name: Docker Build and Upload to AWS ECR
    #   uses: vitr/actions-build-and-upload-to-ecs@v1.0.0
    #   with:
    #     # The AWS access key id
    #     access_key_id: AKIAWOX5NRMU2DUZGRM5
    #     # The AWS secret access key
    #     secret_access_key: IWDqhAG5jLAs/HXYcoN6NUH9uuijEBdPitDdB7iu
    #     # AWS Account ID
    #     account_id: 443986840361
    #     # Name of your ECR repository
    #     repo: public.ecr.aws/x3w3n0r1/docker
    #     # The AWS region
    #     region: ap-southeast-2
