name: Build and push Image to AWS ECR
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Install Docker
      run: | 
        sudo yum install docker -y
        sudo systemctl start docker
        sudo systemctl status docker  
    - name: Build Image 
      run : |
        cd /home/ec2-user/actions-runner/_Docker/Docker/Docker
        sudo docker build -t helloworld .
    - name: pre deployment
      run:  
        aws ecr get-login-password --region ap-southeast-2 | sudo docker login --username AWS --password-stdin 443986840361.dkr.ecr.ap-southeast-2.amazonaws.com
    # - name: Test
    #   run:  
    #     aws ecr batch-delete-image \
    #     --repository-name docker-repository \
    #     --image-ids imageTag=latest
    - name: push to ECR
      run: |    
        sudo docker tag helloworld:latest 443986840361.dkr.ecr.ap-southeast-2.amazonaws.com/docker-repository:latest
        sudo docker push 443986840361.dkr.ecr.ap-southeast-2.amazonaws.com/docker-repository:latest
    - name: Clean Up all
      run: |
        sudo docker rmi -f $(sudo docker images -a -q)
        sudo gpasswd -d $USER docker
        sudo groupdel docker
        sudo yum remove docker -y
